### PR TITLE
Added a Simplified Chinese translation of the README

### PR DESCRIPTION
**Pull request by panjunjie**
Added a Simplified Chinese translation of the README, zh_CN

### CODE REVIEW

**Comment by panjunjie** [comment]
cc @codegangsta

**Comment by panjunjie** [comment]
@meatballhat : Excuse me,why do we not see Simplified Chinese translation of the README?

**Comment by jszwedko** [comment]
Hi @panjunjie,

It is merged, but I see that there wasn't a link included on the English README file. I will add it now.

Thank you!

**Comment by jszwedko** [comment]
Added the link in https://github.com/codegangsta/negroni/commit/41253136e3592bb8f1654186033bcc0c57a5ad70

**Comment by panjunjie** [comment]
Thank you for your reply. I like the project very much

**Pull request merged**
