### PR TITLE
Add convenience func to run with pre-configured *http.Server

### PR DESCRIPTION
**Pull request by debedb**
in particular for Read/Write timeout

### CODE REVIEW

**Comment by socceroos** [comment]
This one is important. I'm using Negroni in our production environment and behind CloudFlare it continues to open file handles (sockets) until it runs out of the max default allocated (1024).

By passing Server options I can force a timeout on ESTABLISHED and keepalive requests so I don't keep hitting my file descriptor limit.

**Comment by debedb** [comment]
@socceroos : I ended up instead doing a workaround in my code like this

```
// RunNegroni is a convenience function that runs the negroni stack as a
// provided HTTP server, with the following caveats:
// 1. the Handler field of the provided serverConfig should be nil,
//    because the Handler used will be the n Negroni object.
func RunNegroni(n *negroni.Negroni, addr string, timeout time.Duration) (*RestServiceInfo, error) {
	svr := &http.Server{Addr: addr, ReadTimeout: timeout, WriteTimeout: timeout}
	l := log.New(os.Stdout, "[negroni] ", 0)
	svr.Handler = n
	svr.ErrorLog = l
	return ListenAndServe(svr)
}
```

See https://github.com/romana/core/blob/c4a8fb6da995f5da8311ef0d2c6435c4d40e7240/common/service.go#L255

**Comment by socceroos** [comment]
Thanks for that! I ended up writing a solution that was very similar, and it seems others have been doing this as well.

**Comment by meatballhat** [comment]
I like the idea of providing a convenient way to run with an existing `*http.Server`, although I'd want some minor changes made to the implementation.  @codegangsta || @jszwedko whaddya think?

**Comment by jszwedko** [comment]
I think you bring up a good point in #106 -- `negroni` aims to be a middleware stack so I don't want to push hard in the direction of being a "server". I almost want to see https://github.com/codegangsta/negroni/pull/107#issuecomment-204784686 as the default way to use `negroni`, but I realize that we already have the convenience functions for starting a real HTTP server providing another which takes a `http.Server` may be desirable.

**Comment by jszwedko** [comment]
Actually, my opinion is that we should keep at as-is with the one convenience `Run` function (to make it easy to spin up and play with) and add directions for using `negroni` with an existing `*http.Server` to the README as the normal usage.

**Comment by jszwedko** [comment]
Added documentation on how to use negroni as an http.Handler which I think is a more flexible way to approach this, but let me know if you have any further thoughts about this @debedb !

**Pull request closed without merging**
