### PR TITLE
README touchup

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by meatballhat** [comment]
ummmm, OK wercker 😺

**Comment by jszwedko** [comment]
❤️

**Comment by jszwedko** [comment]
Oops, I'm sorry, I completely glossed over the fact that you added the middleware docs when I submitted #121 :fearful: 

The rest of this looks great.

**Comment by meatballhat** [comment]
I much preferred your middleware docs!  <3

**Pull request merged**
